import type { CareerClaimVariant, CareerProfileSource } from "./types";

const updatedAt = "2026-08-18T11:22:00.000Z";

export const POST_AUDIT_PROFILE_SOURCES: CareerProfileSource[] = [
  {
    id: "source-post-revised-master",
    label: "Vinnie_Jegathees_Revised_Master_CV.docx",
    sourceType: "CV",
    modifiedAt: "2026-07-23",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_0000000023ac8243baf75e70884aad02",
    notes:
      "Raw File Library source outside the 43-file audit inventory. Contains placeholders and Gartner wording, so it is not canonical.",
  },
  {
    id: "source-post-logitech-original",
    label: "Vinnie_Jegathees_Logitech_Early_Careers_CV.docx",
    sourceType: "CV",
    modifiedAt: "2026-08-08",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_00000000604081f4a3605b8909d885f0",
    notes:
      "Raw File Library application CV. Derivative wording is provenance, not independent verification.",
  },
  {
    id: "source-post-logitech-word-fixed",
    label: "Vinnie_Jegathees_Logitech_Early_Careers_CV_Word_Fixed.docx",
    sourceType: "CV",
    modifiedAt: "2026-08-08",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_00000000a46c81f4a210f0654d6dd3bd",
    notes:
      "Raw File Library application CV. Reintroduces unresolved full Google Project Management certificate wording.",
  },
  {
    id: "source-post-blackrock-product",
    label: "Vinnie_Jegathees_BlackRock_Product_Management_CV.docx",
    sourceType: "CV",
    modifiedAt: "2026-08-13",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_00000000a04481f4b3b9589f59c7b8c8",
    notes:
      "Raw File Library application CV. Contains useful new delivery detail but also Nov 2025 chronology and unsupported UniDrop user-testing/leadership wording.",
  },
  {
    id: "source-post-graduate-project-manager",
    label: "Vinnie_Jegathees_Resume_Reply_Graduate_Project_Manager_No_AI_Hyphens.docx",
    sourceType: "Resume",
    modifiedAt: "2026-08-09",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_00000000278881f49cb3378011b19c2e",
    notes:
      "Raw File Library application resume. Uses safer Google Project Management course wording but repeats Nov 2025 chronology and unsupported UniDrop user-testing/leadership wording.",
  },
  {
    id: "source-post-southeastern-apm-star",
    label: "Vinnie_Jegathees_Southeastern_APM_STAR_Final.docx",
    sourceType: "CV",
    modifiedAt: "2026-08-12",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_0000000031a081f48c7c3cb4f7ad7b8a",
    notes:
      "Raw File Library project-management application CV. Uses Dec 2025 chronology but still includes the unresolved full Google Project Management certificate.",
  },
  {
    id: "source-post-southeastern-assistant",
    label: "Vinnie_Jegathees_Southeastern_Assistant_Project_Manager_CV.pdf",
    sourceType: "CV",
    modifiedAt: "2026-08-12",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_0000000022288246bc3405f2c990d343",
    notes:
      "Raw File Library application CV. Strong project-delivery wording, but derivative metrics and Google certificate/Gartner claims remain evidence-gated.",
  },
  {
    id: "source-post-southeastern-matched-layout",
    label: "Vinnie_Jegathees_Southeastern_Assistant_Project_Manager_CV_Matched_Layout.pdf",
    sourceType: "CV",
    modifiedAt: "2026-08-12",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_0000000094c48246af6a06de187dc808",
    notes:
      "Raw File Library application CV. More cautious metric wording, but unresolved full Google Project Management certificate remains present.",
  },
  {
    id: "source-post-southeastern-assistant-copy",
    label: "Vinnie_Jegathees_Assistant_Project_Manager_CV_Southeastern.pdf",
    sourceType: "CV",
    modifiedAt: "2026-08-13",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    extractionStatus: "Raw extracted",
    trust: "Alternative",
    externalFileId: "file_00000000d57881f4b3b4d7eb7d765648",
    notes:
      "Raw File Library application CV. Closely related to the Southeastern APM family; retained as a separate source but not independent proof.",
  },
];

function variant(input: Omit<CareerClaimVariant, "updatedAt">): CareerClaimVariant {
  return { ...input, updatedAt };
}

export const POST_AUDIT_CLAIM_VARIANTS: CareerClaimVariant[] = [
  variant({
    id: "post-nul-end-nov",
    canonicalKey: "nul-employment-end",
    kind: "Employment",
    label: "Northeastern University London end date",
    value: "Nov 2025 in August product/project-management CVs",
    sourceIds: ["source-post-blackrock-product", "source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Excluded",
    confidence: "High",
    notes: "Superseded by later direct user confirmation of Dec 2025.",
  }),
  variant({
    id: "post-nul-end-present",
    canonicalKey: "nul-employment-end",
    kind: "Employment",
    label: "Northeastern University London end date",
    value: "Present in August Logitech CV variants",
    sourceIds: ["source-post-logitech-original", "source-post-logitech-word-fixed"],
    basis: "Raw source",
    status: "Excluded",
    confidence: "High",
    notes: "Superseded by later direct user confirmation of Dec 2025.",
  }),
  variant({
    id: "post-google-pm-full",
    canonicalKey: "google-project-management-certificate",
    kind: "Certification",
    label: "Google Project Management Professional Certificate",
    value: "Full Professional Certificate listed in August application CVs",
    sourceIds: [
      "source-post-logitech-word-fixed",
      "source-post-southeastern-apm-star",
      "source-post-southeastern-assistant",
      "source-post-southeastern-matched-layout",
      "source-post-southeastern-assistant-copy",
    ],
    basis: "Raw source",
    status: "Conflict",
    confidence: "High",
    notes:
      "Raw derivative CVs prove the wording was used, not that the credential was earned. Primary certificate evidence is still required.",
  }),
  variant({
    id: "post-google-pm-course",
    canonicalKey: "google-project-management-certificate",
    kind: "Certification",
    label: "Google Project Management course",
    value: "Google Project Management course",
    sourceIds: ["source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "Safer than the full-certificate claim, but exact course title/provider still needs certificate evidence.",
  }),
  variant({
    id: "post-nul-ai-chatbot-qa",
    canonicalKey: "nul-ai-chatbot-qa",
    kind: "Achievement",
    label: "Northeastern AI chatbot QA rollout",
    value:
      "Defined QA criteria and supported structured testing of an AI-powered chatbot before go-live",
    sourceIds: ["source-post-blackrock-product", "source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "Potentially useful new experience, but it is absent from the July audit and current canonical evidence bank.",
  }),
  variant({
    id: "post-nul-platform-count",
    canonicalKey: "nul-platform-portfolio",
    kind: "Achievement",
    label: "Northeastern platform portfolio",
    value: "18+ third-party digital platforms",
    sourceIds: [
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
      "source-post-southeastern-assistant",
    ],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "Repeated across derivative application CVs, but repetition is not independent verification.",
  }),
  variant({
    id: "post-idea-pmo-dashboard",
    canonicalKey: "idea-pmo-dashboard",
    kind: "Achievement",
    label: "IDEA StatiCa Power BI PMO dashboard",
    value: "Proposed and built a Power BI PMO dashboard integrating HubSpot and Salesforce",
    sourceIds: [
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
      "source-post-southeastern-apm-star",
      "source-post-southeastern-assistant-copy",
    ],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "The broader Power BI integration is supported. The specific PMO-dashboard framing and personal build depth should be confirmed before approval.",
  }),
  variant({
    id: "post-idea-data-validation",
    canonicalKey: "idea-data-validation",
    kind: "Achievement",
    label: "IDEA StatiCa reporting validation",
    value:
      "Added validation checks across HubSpot/Salesforce reporting before stakeholder reporting",
    sourceIds: [
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
      "source-post-southeastern-apm-star",
      "source-post-southeastern-assistant-copy",
    ],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "Useful delivery/QA detail, but new to the post-audit CV family and not yet independently corroborated.",
  }),
  variant({
    id: "post-buchanan-ats-automation",
    canonicalKey: "buchanan-ats-automation",
    kind: "Achievement",
    label: "Buchanan ATS automation",
    value:
      "Automated recruitment workflows and reconfigured the ATS to reduce duplicate work and improve candidate-status visibility",
    sourceIds: [
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
      "source-post-southeastern-apm-star",
      "source-post-southeastern-assistant-copy",
    ],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes:
      "Preserved as potentially useful experience pending primary or historical-source corroboration.",
  }),
  variant({
    id: "post-buchanan-omnichannel-qa",
    canonicalKey: "buchanan-omnichannel-qa",
    kind: "Achievement",
    label: "Buchanan omnichannel campaign QA",
    value: "Led an omnichannel recruitment campaign and introduced QA audits before launch",
    sourceIds: ["source-post-blackrock-product", "source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Low",
    notes:
      "Leadership wording is not approved until corroborated beyond derivative application CVs.",
  }),
  variant({
    id: "post-nas-journey-qa",
    canonicalKey: "nas-customer-journey-qa",
    kind: "Achievement",
    label: "National Autistic Society journey QA",
    value: "Mapped campaign/customer journeys and introduced QA standards across touchpoints",
    sourceIds: [
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
      "source-post-southeastern-apm-star",
    ],
    basis: "Raw source",
    status: "Needs Evidence",
    confidence: "Medium",
    notes: "New post-audit delivery detail. Keep evidence-gated until corroborated.",
  }),
  variant({
    id: "post-unidrop-user-research",
    canonicalKey: "unidrop-user-research",
    kind: "Project",
    label: "UniDrop user testing and validation",
    value:
      "Used user testing, questionnaires, heatmap analysis and participant feedback to validate the problem statement",
    sourceIds: ["source-post-blackrock-product", "source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Excluded",
    confidence: "High",
    notes:
      "Blocked because the July evidence audit found no attributable user-research/testing proof for UniDrop.",
  }),
  variant({
    id: "post-unidrop-leadership",
    canonicalKey: "unidrop-project-leadership",
    kind: "Project",
    label: "UniDrop project leadership",
    value: "Led project scoping for UniDrop",
    sourceIds: ["source-post-blackrock-product", "source-post-graduate-project-manager"],
    basis: "Raw source",
    status: "Excluded",
    confidence: "High",
    notes:
      "The project is safely attributable as an academic concept, but individual leadership of the group work is not established by stronger evidence.",
  }),
  variant({
    id: "post-bioprinting-final-frameworks",
    canonicalKey: "bioprinting-final-frameworks",
    kind: "Project",
    label: "3D Bioprinting final assessed frameworks",
    value: "TRL, AD² and S-curve",
    sourceIds: [
      "source-audit-2026-07-23",
      "source-post-blackrock-product",
      "source-post-graduate-project-manager",
    ],
    basis: "Raw source",
    status: "Approved",
    confidence: "High",
    notes: "Consistent with the strongest final-report evidence identified by the July audit.",
  }),
  variant({
    id: "post-bioprinting-gartner",
    canonicalKey: "bioprinting-final-frameworks",
    kind: "Project",
    label: "3D Bioprinting Gartner wording",
    value: "TRL and Gartner Hype Cycle",
    sourceIds: [
      "source-post-revised-master",
      "source-post-logitech-original",
      "source-post-logitech-word-fixed",
      "source-post-southeastern-assistant",
    ],
    basis: "Raw source",
    status: "Excluded",
    confidence: "High",
    notes:
      "Derivative CV wording is weaker than the final-report evidence. Do not present Gartner as the assessed final framework without separate proof.",
  }),
];
