import type {
  CareerClaimVariant,
  CareerOsData,
  CareerProfileItem,
  CareerProfileSource,
} from "./types";

const updatedAt = "2026-08-18T11:05:00.000Z";

function variant(
  input: Omit<CareerClaimVariant, "updatedAt">,
): CareerClaimVariant {
  return { ...input, updatedAt };
}

export const PROFILE_CLAIM_VARIANTS: CareerClaimVariant[] = [
  variant({
    id: "cv-nul-end-current",
    canonicalKey: "nul-employment-end",
    kind: "Employment",
    label: "Northeastern University London end date",
    value: "Present in the 31 May 2026 master CV",
    sourceIds: ["source-m01"],
    basis: "Raw source",
    status: "Excluded",
    confidence: "Medium",
    notes: "Superseded by later direct user confirmation in CareerOS.",
  }),
  variant({
    id: "register-nul-end-nov",
    canonicalKey: "nul-employment-end",
    kind: "Employment",
    label: "Northeastern University London end date",
    value: "Nov 2025 in older CareerOS registers",
    sourceIds: ["source-evidence-bank", "source-master-profile-register"],
    basis: "CareerOS register",
    status: "Excluded",
    confidence: "Medium",
    notes: "Superseded by later direct user confirmation.",
  }),
  variant({
    id: "user-nul-end-dec",
    canonicalKey: "nul-employment-end",
    kind: "Employment",
    label: "Northeastern University London end date",
    value: "Dec 2025",
    sourceIds: ["source-user-confirmation-2026-08-16"],
    basis: "User confirmation",
    status: "Approved",
    confidence: "High",
  }),
  variant({
    id: "nul-qualified-leads-40",
    canonicalKey: "nul-qualified-leads",
    kind: "Achievement",
    label: "Northeastern qualified leads",
    value: "40%+ uplift in qualified leads",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
    notes: "Repeated/current claim, but dashboard period and attribution are not yet locked.",
  }),
  variant({
    id: "nul-budget-140k",
    canonicalKey: "nul-digital-media-budget",
    kind: "Achievement",
    label: "Northeastern digital media budget",
    value: "£140k+ annual digital media budget",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16", "source-metrics-register"],
    basis: "User confirmation",
    status: "Approved",
    confidence: "High",
  }),
  variant({
    id: "nul-cpl-range",
    canonicalKey: "nul-cpl-range",
    kind: "Achievement",
    label: "Northeastern CPL range",
    value: "£3 to £646 CPL variation",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nul-efficiency-35",
    canonicalKey: "nul-efficiency-improvement",
    kind: "Achievement",
    label: "Northeastern efficiency improvement",
    value: "35% efficiency improvement",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nul-roi-28-cvr-20",
    canonicalKey: "nul-roi-conversion",
    kind: "Achievement",
    label: "Northeastern ROI and conversion",
    value: "28% ROI improvement and 20% conversion uplift",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nul-agency-effectiveness",
    canonicalKey: "nul-agency-effectiveness",
    kind: "Achievement",
    label: "Northeastern agency performance",
    value: "23% campaign-effectiveness uplift and 25% YoY CPA reduction",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Low",
  }),
  variant({
    id: "nul-landing-pages-30",
    canonicalKey: "nul-landing-page-volume",
    kind: "Achievement",
    label: "Northeastern landing pages",
    value: "30+ campaign landing pages",
    sourceIds: ["source-m01", "source-m02", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nul-landing-cvr-27",
    canonicalKey: "nul-landing-page-conversion",
    kind: "Achievement",
    label: "Northeastern landing-page conversion",
    value: "27% conversion increase",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16", "source-metrics-register"],
    basis: "User confirmation",
    status: "Approved",
    confidence: "High",
  }),
  variant({
    id: "idea-efficiency-20",
    canonicalKey: "idea-operational-efficiency",
    kind: "Achievement",
    label: "IDEA StatiCa operational efficiency",
    value: "20% client operational-efficiency improvement",
    sourceIds: ["source-m01", "source-m10", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Low",
  }),
  variant({
    id: "idea-conversion-roi",
    canonicalKey: "idea-conversion-roi",
    kind: "Achievement",
    label: "IDEA StatiCa conversion and ROI",
    value: "15% conversion uplift and 36% ROI improvement",
    sourceIds: ["source-m01", "source-m10", "source-m11", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "idea-completion-25",
    canonicalKey: "idea-delivery-improvement",
    kind: "Achievement",
    label: "IDEA StatiCa delivery improvement",
    value: "25% project-completion improvement",
    sourceIds: ["source-m01", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "idea-productivity-30",
    canonicalKey: "idea-delivery-improvement",
    kind: "Achievement",
    label: "IDEA StatiCa delivery improvement",
    value: "30% team-productivity increase",
    sourceIds: ["source-m09", "source-m10"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "idea-productivity-29",
    canonicalKey: "idea-delivery-improvement",
    kind: "Achievement",
    label: "IDEA StatiCa delivery improvement",
    value: "29% productivity improvement",
    sourceIds: ["source-audit-2026-07-23"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "idea-prospecting",
    canonicalKey: "idea-prospecting-performance",
    kind: "Achievement",
    label: "IDEA StatiCa prospecting performance",
    value: "32% response-rate improvement and 15% conversion uplift",
    sourceIds: ["source-m01", "source-m10", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "idea-organic-traffic",
    canonicalKey: "idea-organic-traffic",
    kind: "Achievement",
    label: "IDEA StatiCa organic traffic",
    value: "20% organic traffic growth",
    sourceIds: ["source-m10", "source-m11", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Low",
  }),
  variant({
    id: "idea-ai-attribution",
    canonicalKey: "idea-organic-traffic-ai-attribution",
    kind: "Achievement",
    label: "IDEA StatiCa AI analytics attribution",
    value: "AI analytics tools caused 20% organic traffic growth",
    sourceIds: ["source-m11"],
    basis: "Evidence audit",
    status: "Excluded",
    confidence: "Low",
    notes: "Audit explicitly says to remove the AI attribution.",
  }),
  variant({
    id: "buchanan-crm-metrics",
    canonicalKey: "buchanan-crm-performance",
    kind: "Achievement",
    label: "Buchanan CRM migration performance",
    value: "62% engagement increase and 23% marketing-cost reduction",
    sourceIds: ["source-m01", "source-m10", "source-m11", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "buchanan-time-fill-20",
    canonicalKey: "buchanan-time-to-fill",
    kind: "Achievement",
    label: "Buchanan time-to-fill",
    value: "20% time-to-fill reduction",
    sourceIds: ["source-m01", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "buchanan-time-hire-25",
    canonicalKey: "buchanan-time-to-fill",
    kind: "Achievement",
    label: "Buchanan time-to-fill",
    value: "25% time-to-hire reduction",
    sourceIds: ["source-m10"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "buchanan-collateral-30",
    canonicalKey: "buchanan-collateral-engagement",
    kind: "Achievement",
    label: "Buchanan collateral engagement",
    value: "30% engagement uplift",
    sourceIds: ["source-m01", "source-m10", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nas-paid-search-30-60",
    canonicalKey: "nas-paid-search-performance",
    kind: "Achievement",
    label: "National Autistic Society paid-search performance",
    value: "30% click increase and 60% impression increase",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16", "source-metrics-register"],
    basis: "User confirmation",
    status: "Approved",
    confidence: "High",
  }),
  variant({
    id: "nas-roas-440",
    canonicalKey: "nas-100k-roas",
    kind: "Achievement",
    label: "National Autistic Society 100K Running Challenge",
    value: "440% ROAS",
    sourceIds: ["source-m09", "source-m10", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "nas-donor-23",
    canonicalKey: "nas-donor-base",
    kind: "Achievement",
    label: "National Autistic Society donor-base growth",
    value: "23% donor-base increase",
    sourceIds: ["source-m09"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "nas-donor-42",
    canonicalKey: "nas-donor-base",
    kind: "Achievement",
    label: "National Autistic Society donor-base growth",
    value: "42% donor-base increase",
    sourceIds: ["source-m10"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "nas-reach-500k",
    canonicalKey: "nas-awareness-reach",
    kind: "Achievement",
    label: "National Autistic Society awareness reach",
    value: "500,000+ people reached",
    sourceIds: ["source-m09", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Low",
  }),
  variant({
    id: "infinite-ticket-800",
    canonicalKey: "infinite-ticket-volume",
    kind: "Achievement",
    label: "Infinite Entertainment ticket sales",
    value: "800+ ticket sales per event",
    sourceIds: ["source-m01", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "infinite-uplift-20",
    canonicalKey: "infinite-ticket-uplift",
    kind: "Achievement",
    label: "Infinite Entertainment ticket-sales uplift",
    value: "20% ticket-sales uplift",
    sourceIds: ["source-m01", "source-m10"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "infinite-uplift-30",
    canonicalKey: "infinite-ticket-uplift",
    kind: "Achievement",
    label: "Infinite Entertainment ticket-sales uplift",
    value: "30% ticket-sales uplift",
    sourceIds: ["source-d21", "source-d22"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "infinite-uplift-50",
    canonicalKey: "infinite-ticket-uplift",
    kind: "Achievement",
    label: "Infinite Entertainment ticket-sales uplift",
    value: "50% ticket-sales uplift",
    sourceIds: ["source-m11", "source-d21", "source-d22"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "infinite-aggregate-tickets",
    canonicalKey: "infinite-aggregate-events",
    kind: "Achievement",
    label: "Infinite Entertainment aggregate event history",
    value: "20,000 tickets and 10,000+ attendees across six seasons",
    sourceIds: ["source-m10", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Needs Evidence",
    confidence: "Low",
  }),
  variant({
    id: "infinite-ad-waste-18",
    canonicalKey: "infinite-ad-waste",
    kind: "Achievement",
    label: "Infinite Entertainment predictive analytics",
    value: "18% less ad waste",
    sourceIds: ["source-m11", "source-metrics-register"],
    basis: "Evidence audit",
    status: "Excluded",
    confidence: "Low",
  }),
  variant({
    id: "apm-pfq-verified",
    canonicalKey: "apm-pfq",
    kind: "Certification",
    label: "APM Project Fundamentals Qualification (PFQ)",
    value: "Issued 13 January 2025 by the Association for Project Management",
    sourceIds: ["source-apm-pfq-primary", "source-education-register"],
    basis: "Primary evidence",
    status: "Approved",
    confidence: "High",
  }),
  variant({
    id: "google-pm-full",
    canonicalKey: "google-project-management-certificate",
    kind: "Certification",
    label: "Google Project Management Professional Certificate",
    value: "Full Professional Certificate completed",
    sourceIds: ["source-m11", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "google-pm-foundations",
    canonicalKey: "google-project-management-certificate",
    kind: "Certification",
    label: "Google Foundations of Project Management",
    value: "Foundations of Project Management course completion claim",
    sourceIds: ["source-m07", "source-m10", "source-education-register"],
    basis: "CareerOS register",
    status: "Needs Evidence",
    confidence: "Medium",
  }),
  variant({
    id: "prince2-foundation-completed",
    canonicalKey: "prince2-foundation",
    kind: "Certification",
    label: "PRINCE2 Foundation",
    value: "Completed",
    sourceIds: ["source-m10", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "prince2-foundation-ongoing",
    canonicalKey: "prince2-foundation",
    kind: "Certification",
    label: "PRINCE2 Foundation",
    value: "Ongoing / unresolved",
    sourceIds: ["source-m11", "source-education-register"],
    basis: "CareerOS register",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "ga-date-2021",
    canonicalKey: "google-analytics-training-date",
    kind: "Certification",
    label: "Google Analytics 3 & 4",
    value: "Feb 2021",
    sourceIds: ["source-audit-2026-07-23", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "ga-date-2022",
    canonicalKey: "google-analytics-training-date",
    kind: "Certification",
    label: "Google Analytics 3 & 4",
    value: "Feb 2022",
    sourceIds: ["source-audit-2026-07-23", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "hotjar-date-2023",
    canonicalKey: "hotjar-training-date",
    kind: "Certification",
    label: "Hotjar Levels 1 & 2",
    value: "2023",
    sourceIds: ["source-audit-2026-07-23", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "hotjar-date-2024",
    canonicalKey: "hotjar-training-date",
    kind: "Certification",
    label: "Hotjar Levels 1 & 2",
    value: "Apr 2024",
    sourceIds: ["source-audit-2026-07-23", "source-education-register"],
    basis: "Evidence audit",
    status: "Conflict",
    confidence: "Low",
  }),
  variant({
    id: "people-management-d20",
    canonicalKey: "formal-people-management",
    kind: "Achievement",
    label: "Formal people management",
    value: "Managed teams and delegated tasks based on skillset and expertise",
    sourceIds: ["source-d20", "source-audit-2026-07-23", "source-evidence-bank"],
    basis: "Evidence audit",
    status: "Excluded",
    confidence: "Low",
    notes: "No reviewed source establishes direct reports or formal line-management responsibility.",
  }),
  variant({
    id: "intentionally-distributed-team",
    canonicalKey: "intentionally-team-management",
    kind: "Project",
    label: "Intentionally team management",
    value: "Managed a distributed team across three regions",
    sourceIds: ["source-m11", "source-evidence-bank"],
    basis: "Evidence audit",
    status: "Excluded",
    confidence: "Low",
    notes: "Conflicts with later solo-founder evidence.",
  }),
];

export function approvedProfileItems(data: CareerOsData): CareerProfileItem[] {
  return (data.profileItems ?? []).filter((item) => item.status === "Approved");
}

export function unresolvedVariantKeys(variants: CareerClaimVariant[]): string[] {
  const groups = new Map<string, CareerClaimVariant[]>();
  variants.forEach((item) => groups.set(item.canonicalKey, [...(groups.get(item.canonicalKey) ?? []), item]));

  return [...groups.entries()]
    .filter(([, items]) => {
      const hasApproved = items.some((item) => item.status === "Approved");
      const hasBlocked = items.some((item) => item.status === "Conflict" || item.status === "Excluded");
      return !hasApproved && hasBlocked;
    })
    .map(([key]) => key)
    .sort();
}

export interface ExtractionCoverage {
  totalAuditSources: number;
  reconciled: number;
  rawExtracted: number;
  auditOnly: number;
  missingRaw: number;
  excluded: number;
}

export function extractionCoverage(sources: CareerProfileSource[]): ExtractionCoverage {
  const auditSources = sources.filter((source) => Boolean(source.auditId));
  const count = (status: CareerProfileSource["extractionStatus"]) =>
    auditSources.filter((source) => source.extractionStatus === status).length;

  const reconciled = count("Reconciled");
  const rawOnly = count("Raw extracted");

  return {
    totalAuditSources: auditSources.length,
    reconciled,
    rawExtracted: reconciled + rawOnly,
    auditOnly: count("Audit only"),
    missingRaw: count("Missing raw file"),
    excluded: count("Excluded"),
  };
}

export function variantsByCanonicalKey(
  variants: CareerClaimVariant[],
): Map<string, CareerClaimVariant[]> {
  const groups = new Map<string, CareerClaimVariant[]>();
  variants.forEach((item) => groups.set(item.canonicalKey, [...(groups.get(item.canonicalKey) ?? []), item]));
  return groups;
}
