import type { CareerProfileItem, CareerProfileSource } from "./types";

const updatedAt = "2026-08-18T10:45:00.000Z";

export const PROFILE_SOURCES: CareerProfileSource[] = [
  {
    id: "source-audit-2026-07-23",
    label: "Vinnie CV Evidence Audit",
    sourceType: "Evidence Audit",
    modifiedAt: "2026-07-23",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    trust: "Evidence",
    notes:
      "Evidence comparison covering 43 career and application documents plus targeted project evidence.",
  },
  {
    id: "source-user-confirmation-2026-08-16",
    label: "CareerOS factual confirmation, 16 Aug 2026",
    sourceType: "User Confirmation",
    modifiedAt: "2026-08-16",
    ownership: "User confirmed",
    ingestionStatus: "Imported",
    trust: "Evidence",
    notes: "Direct factual confirmation used by the audited CareerOS seed.",
  },
  {
    id: "source-m01",
    auditId: "M01",
    label: "VINNIE JEGATHEES !!.docx",
    sourceType: "CV",
    modifiedAt: "2026-05-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Imported",
    trust: "Canonical",
    notes: "Most current working CV; retained as canonical copy",
  },
  {
    id: "source-m02",
    auditId: "M02",
    label: "Vinnie_Jegathees_CV_Technology_Projects_Updated_Desktop_Copy.docx",
    sourceType: "CV",
    modifiedAt: "2026-06-01",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Alternative",
    notes: "Recent alternative; small wording differences, not authoritative over M01",
  },
  {
    id: "source-m03",
    auditId: "M03",
    label: "Vinnie Jegathees CV  .docx",
    sourceType: "CV",
    modifiedAt: "2026-05-27",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Alternative",
    notes: "Recent alternative; superseded by M01",
  },
  {
    id: "source-m04",
    auditId: "M04",
    label: "Vinnie_Jegathees_CV_Redraft_Claude.docx",
    sourceType: "CV",
    modifiedAt: "2026-05-27",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Alternative",
    notes: "Draft; use only where corroborated",
  },
  {
    id: "source-m05",
    auditId: "M05",
    label: "Vinnie_Jegathees_Technology_Management_CV_Redraft.docx",
    sourceType: "CV",
    modifiedAt: "2026-05-27",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Alternative",
    notes: "Draft; superseded by M01",
  },
  {
    id: "source-m06",
    auditId: "M06",
    label: "Vinnie_Jegathees_CV_chat.docx",
    sourceType: "CV",
    modifiedAt: "2026-05-27",
    ownership: "Confirmed mine",
    ingestionStatus: "Excluded",
    trust: "Unsafe",
    notes:
      "Unsafe draft: placeholder contact data and unsupported chronology; contributes no disputed facts",
  },
  {
    id: "source-m07",
    auditId: "M07",
    label: "Vinnie Jegathees.docx",
    sourceType: "CV",
    modifiedAt: "2025-04-14",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes:
      "Outdated application version; useful for LinkedIn URL and historical certification wording",
  },
  {
    id: "source-m08",
    auditId: "M08",
    label: "Vinnie Jegathees - Performance Marketing Manager CV.docx",
    sourceType: "CV",
    modifiedAt: "2025-05-22",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated for chronology; strong contact and LinkedIn evidence",
  },
  {
    id: "source-m09",
    auditId: "M09",
    label: "Vinnie Jegathees Cover Letter.docx",
    sourceType: "Cover Letter",
    modifiedAt: "2025-01-20",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Historical application evidence; contains useful named-campaign context",
  },
  {
    id: "source-m10",
    auditId: "M10",
    label: "Vinnie Jegathees Resume - CETR Project Support Officer.docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Historical and heavily tailored; useful for date and certification conflicts",
  },
  {
    id: "source-m11",
    auditId: "M11",
    label: "JegatheeswaranV_PersonalStatement_MScTechMgmt_UCL.docx",
    sourceType: "Personal Statement",
    modifiedAt: "2025-06-12",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Application-stage narrative; several claims conflict with later project evidence",
  },
  {
    id: "source-h01",
    auditId: "H01",
    label: "Vitharsan Jegatheeswaran CV.docx",
    sourceType: "CV",
    modifiedAt: "2023-03-30",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated; useful only for historical conflicts",
  },
  {
    id: "source-h02",
    auditId: "H02",
    label: "Vitharsan Jegatheeswaran Resume (3) (1).docx",
    sourceType: "Resume",
    modifiedAt: "2023-04-14",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h03",
    auditId: "H03",
    label: "Vitharsan Jegatheeswaran Resume (3).docx",
    sourceType: "Resume",
    modifiedAt: "2023-04-14",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h04",
    auditId: "H04",
    label: "Vitharsan Jegatheeswaran Resume (4).docx",
    sourceType: "Resume",
    modifiedAt: "2023-05-16",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h05",
    auditId: "H05",
    label: "Vitharsan Jegatheeswaran Resume (6).docx",
    sourceType: "Resume",
    modifiedAt: "2023-05-18",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h06",
    auditId: "H06",
    label: "Vitharsan+Jegatheeswaran+Resume (1).docx",
    sourceType: "Resume",
    modifiedAt: "2023-04-09",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h07",
    auditId: "H07",
    label: "Vitharsan+Jegatheeswaran+Resume (3).docx",
    sourceType: "Resume",
    modifiedAt: "2023-04-25",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h08",
    auditId: "H08",
    label: "Vitharsan+Jegatheeswaran+Resume+%284%29.docx",
    sourceType: "Resume",
    modifiedAt: "2023-05-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h09",
    auditId: "H09",
    label: "Vitharsan+Jegatheeswaran+Resume+(4) (1).docx",
    sourceType: "Resume",
    modifiedAt: "2023-05-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-h10",
    auditId: "H10",
    label: "Vitharsan+Jegatheeswaran+Resume-2.docx",
    sourceType: "Resume",
    modifiedAt: "2023-05-18",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d01",
    auditId: "D01",
    label: "VINNIE JEGATHEES RESUME.docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-09",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d02",
    auditId: "D02",
    label: "VINNIE JEGATHEES RESUME (2).docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d03",
    auditId: "D03",
    label: "Vinnie Jegathees CV .docx",
    sourceType: "CV",
    modifiedAt: "2025-01-18",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d04",
    auditId: "D04",
    label: "VINNIE JEGATHEES RESUME (3).docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-30",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d05",
    auditId: "D05",
    label: "VINNIE JEGATHEES RESUME (4).docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-30",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d06",
    auditId: "D06",
    label: "VINNIE JEGATHEES RESUME (5).docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d07",
    auditId: "D07",
    label: "VINNIE JEGATHEES RESUME (7).docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d08",
    auditId: "D08",
    label: "VINNIE JEGATHEES RESUME-2.docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d09",
    auditId: "D09",
    label: "VINNIE JEGATHEES RESUME-3.docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d10",
    auditId: "D10",
    label: "VINNIE JEGATHEES RESUME-5.docx",
    sourceType: "Resume",
    modifiedAt: "2025-01-31",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d11",
    auditId: "D11",
    label: "VINNIE%20JEGATHEES%20RESUME-4.docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-01",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d12",
    auditId: "D12",
    label: "VINNIE JEGATHEES RESUME (8).docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-04",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d13",
    auditId: "D13",
    label: "VINNIE JEGATHEES RESUME (9).docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-04",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d14",
    auditId: "D14",
    label: "VINNIE JEGATHEES RESUME (16).docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-07",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated; useful for course-status wording",
  },
  {
    id: "source-d15",
    auditId: "D15",
    label: "VINNIE JEGATHEES RESUME _2 (1).docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-07",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d16",
    auditId: "D16",
    label: "VINNIE-JEGATHEES-RESUME-2.docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-15",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d17",
    auditId: "D17",
    label: "VINNIE-JEGATHEES-RESUME-Project%20Manager%20(Content%20growth).docx",
    sourceType: "Resume",
    modifiedAt: "2025-02-16",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated and heavily tailored",
  },
  {
    id: "source-d18",
    auditId: "D18",
    label: "VINNIE%20JEGATHEES%20RESUME-8.docx",
    sourceType: "Resume",
    modifiedAt: "2025-04-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d19",
    auditId: "D19",
    label: "VINNIE%20JEGATHEES%20RESUME-9.docx",
    sourceType: "Resume",
    modifiedAt: "2025-04-17",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated variant",
  },
  {
    id: "source-d20",
    auditId: "D20",
    label: "VINNIE JEGATHEES RESUME (17).docx",
    sourceType: "Resume",
    modifiedAt: "2025-04-25",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated; contains unsupported generic team-management wording",
  },
  {
    id: "source-d21",
    auditId: "D21",
    label: "Vinnie Jegathees CV  (1).docx",
    sourceType: "CV",
    modifiedAt: "2024-11-02",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated; useful for older metric versions",
  },
  {
    id: "source-d22",
    auditId: "D22",
    label: "Vinnie%20Jegathees%20CV%20-10.docx",
    sourceType: "CV",
    modifiedAt: "2024-11-01",
    ownership: "Confirmed mine",
    ingestionStatus: "Indexed",
    trust: "Historical",
    notes: "Outdated; useful for older metric versions",
  },
];

export const PROFILE_ITEMS: CareerProfileItem[] = [
  {
    id: "pi-nul-chronology",
    kind: "Employment",
    label: "Northeastern University London chronology",
    value: "Performance Marketing Manager (Contract), Jun 2025 – Dec 2025",
    safeWording:
      "Performance Marketing Manager (Contract) | Northeastern University London | Jun 2025 – Dec 2025",
    sourceIds: ["source-m01", "source-audit-2026-07-23", "source-user-confirmation-2026-08-16"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    notes:
      "The latest CV says Present. CareerOS keeps the later user-confirmed end date rather than silently copying the CV wording.",
    updatedAt,
  },
  {
    id: "pi-budget",
    kind: "Achievement",
    label: "Northeastern annual digital media budget",
    value: "£140k+ annual digital media budget",
    safeWording:
      "Managed a £140k+ annual digital media budget across PPC, paid social, display and third-party platforms.",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16"],
    evidenceIds: ["ev-budget"],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-nul-cvr",
    kind: "Achievement",
    label: "Northeastern landing-page conversion improvement",
    value: "27% increase in conversion rates",
    safeWording:
      "Partnered with website and stakeholder teams on landing-page and A/B testing activity, increasing conversion rates by 27%.",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16"],
    evidenceIds: ["ev-cvr"],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-idea-adoption",
    kind: "Achievement",
    label: "IDEA StatiCa enterprise software adoption",
    value: "Enterprise software-adoption projects with structural-engineering firms",
    safeWording:
      "Delivered enterprise software-adoption projects with structural-engineering clients, covering engagement, milestones and training.",
    sourceIds: ["source-m01", "source-audit-2026-07-23"],
    evidenceIds: ["ev-adoption"],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-nas-paid-search",
    kind: "Achievement",
    label: "National Autistic Society paid-search improvement",
    value: "30% increase in clicks and 60% increase in impressions",
    safeWording:
      "Rebuilt underperforming paid-search content and keyword strategy with an external agency, increasing clicks by 30% and impressions by 60%.",
    sourceIds: ["source-m01", "source-user-confirmation-2026-08-16"],
    evidenceIds: ["ev-nas"],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-intentionally",
    kind: "Project",
    label: "Intentionally",
    value: "Founder-led mobile-first dating MVP",
    safeWording:
      "Founded and led product development for Intentionally, a mobile-first dating MVP centred on guided Vibe Checks, mutual Continue or Pass and safety; defined the core journey, MVP scope, roadmap and product documentation, and developed a clickable prototype using a Next.js and Supabase project stack.",
    sourceIds: ["source-audit-2026-07-23", "source-m01"],
    evidenceIds: ["ev-intentionally"],
    status: "Approved",
    confidence: "High",
    notes:
      "Pre-commercial founder project. Do not claim paying users, a managed team, commercial performance or production-grade delivery.",
    updatedAt,
  },
  {
    id: "pi-unidrop",
    kind: "Project",
    label: "UniDrop",
    value: "UCL academic AI-enabled campus logistics concept",
    safeWording:
      "Developed a UCL academic concept for an AI-enabled campus logistics service, applying new-product-development, business-model and technology-evaluation frameworks.",
    sourceIds: ["source-audit-2026-07-23", "source-m01"],
    evidenceIds: ["ev-npd"],
    status: "Approved",
    confidence: "High",
    notes:
      "Academic concept only. The audit does not support claiming implemented autonomous delivery hardware, software or validated user-research results.",
    updatedAt,
  },
  {
    id: "pi-bioprinting",
    kind: "Project",
    label: "3D Bioprinting",
    value: "UCL group emerging-technology review",
    safeWording:
      "Contributed to a UCL group emerging-technology review of 3D bioprinting, applying TRL and AD², market, risk and roadmapping frameworks across near-, medium- and long-term applications.",
    sourceIds: ["source-audit-2026-07-23", "source-m01"],
    evidenceIds: ["ev-trl"],
    status: "Approved",
    confidence: "High",
    notes:
      "The final report is stronger evidence than the CV wording. Gartner Hype Cycle should not be promoted without separate assessed evidence.",
    updatedAt,
  },
  {
    id: "pi-atlas",
    kind: "Project",
    label: "Atlas",
    value: "Internal founder decision-support concept and static prototype",
    safeWording:
      "Defined and prototyped an internal founder review and decision-support concept, producing a static prototype, evidence-first product specification and gated prototype-to-production roadmap.",
    sourceIds: ["source-audit-2026-07-23"],
    evidenceIds: ["ev-atlas"],
    status: "Approved",
    confidence: "Medium",
    notes:
      "Static prototype and planning evidence only. Do not describe Atlas as an operational or commercial platform.",
    updatedAt,
  },
  {
    id: "pi-google-pm-certificate",
    kind: "Certification",
    label: "Google Project Management Professional Certificate",
    value: "Google Project Management Professional Certificate, Nov 2024",
    sourceIds: ["source-m07", "source-m10", "source-m11", "source-audit-2026-07-23"],
    evidenceIds: [],
    status: "Conflict",
    confidence: "Low",
    notes:
      "The audit says the evidence supports the foundation-course title only unless the full certificate is produced. Keep the full certificate wording out of generated documents until resolved.",
    updatedAt,
  },
  {
    id: "pi-team-management",
    kind: "Achievement",
    label: "Formal people management",
    value: "Managed a team",
    sourceIds: ["source-d20", "source-audit-2026-07-23"],
    evidenceIds: [],
    status: "Excluded",
    confidence: "Low",
    notes:
      "No reviewed source establishes direct reports or formal line-management responsibility. Campaign, project, stakeholder and agency leadership remain usable.",
    updatedAt,
  },
];
