import type { CareerProfileItem } from "./types";

const updatedAt = "2026-08-18T11:10:00.000Z";

export const PROFILE_RECONCILED_ITEMS: CareerProfileItem[] = [
  {
    id: "pi-professional-summary",
    kind: "Identity",
    label: "Professional summary",
    value:
      "Experienced digital and performance marketing and operations professional transitioning towards product, project delivery, technology consulting, digital transformation, innovation and product marketing roles.",
    safeWording:
      "Experienced digital and performance marketing professional with operations and technology-management experience, combining multi-market acquisition, analytics, stakeholder coordination, project delivery, product concept development and technology evaluation.",
    sourceIds: ["source-master-profile-register", "source-m01", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-idea-chronology",
    kind: "Employment",
    label: "IDEA StatiCa UK chronology",
    value: "Marketing & Operations Executive (Contract), Sep 2023 – Jun 2024",
    safeWording:
      "Marketing & Operations Executive (Contract) | IDEA StatiCa UK | Sep 2023 – Jun 2024",
    sourceIds: ["source-m01", "source-audit-2026-07-23", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-buchanan-chronology",
    kind: "Employment",
    label: "Buchanan Staffing Group chronology",
    value: "Senior Digital Marketing Executive (Contract), Feb 2023 – May 2023",
    safeWording:
      "Senior Digital Marketing Executive (Contract) | Buchanan Staffing Group | Feb 2023 – May 2023",
    sourceIds: ["source-m01", "source-audit-2026-07-23", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-nas-chronology",
    kind: "Employment",
    label: "National Autistic Society chronology",
    value: "Digital Advertising Officer, Apr 2022 – Feb 2023",
    safeWording: "Digital Advertising Officer | National Autistic Society | Apr 2022 – Feb 2023",
    sourceIds: ["source-m01", "source-audit-2026-07-23", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-infinite-chronology",
    kind: "Employment",
    label: "Infinite Entertainment UK chronology",
    value: "Senior Digital Marketing Executive, Jun 2016 – Apr 2022",
    safeWording:
      "Senior Digital Marketing Executive | Infinite Entertainment UK | Jun 2016 – Apr 2022",
    sourceIds: ["source-m01", "source-audit-2026-07-23", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-ucl-msc",
    kind: "Education",
    label: "MSc Technology Management",
    value: "MSc Technology Management, University College London, part-time, in progress",
    safeWording: "MSc Technology Management (Part-time), University College London | In progress.",
    sourceIds: ["source-m01", "source-education-register", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    notes: "Start and expected completion dates are not locked. Do not invent dates.",
    updatedAt,
  },
  {
    id: "pi-essex-bsc",
    kind: "Education",
    label: "BSc Marketing and Management",
    value: "BSc Marketing and Management (2:1), University of Essex, 2020",
    safeWording: "BSc Marketing and Management (2:1), University of Essex, 2020.",
    sourceIds: ["source-m01", "source-education-register", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    updatedAt,
  },
  {
    id: "pi-apm-pfq",
    kind: "Certification",
    label: "APM Project Fundamentals Qualification (PFQ)",
    value:
      "APM Project Fundamentals Qualification (PFQ), Association for Project Management, issued 13 January 2025",
    safeWording:
      "APM Project Fundamentals Qualification (PFQ), Association for Project Management, 2025.",
    sourceIds: ["source-apm-pfq-primary", "source-education-register", "source-evidence-bank"],
    evidenceIds: [],
    status: "Approved",
    confidence: "High",
    notes: "Primary CareerOS record is based on the user-provided Credly badge.",
    updatedAt,
  },
  {
    id: "pi-ga-training",
    kind: "Certification",
    label: "Google Analytics 3 & 4",
    value: "Google Analytics 3 & 4 training",
    safeWording: "Google Analytics 3 & 4.",
    sourceIds: ["source-m01", "source-education-register"],
    evidenceIds: [],
    status: "Approved",
    confidence: "Medium",
    notes:
      "Current CV-level training evidence supports the title. Do not add a provider or date until verified.",
    updatedAt,
  },
  {
    id: "pi-hotjar-training",
    kind: "Certification",
    label: "Hotjar Levels 1 & 2",
    value: "Hotjar Levels 1 & 2 training",
    safeWording: "Hotjar Levels 1 & 2.",
    sourceIds: ["source-m01", "source-education-register"],
    evidenceIds: [],
    status: "Approved",
    confidence: "Medium",
    notes: "Current CV-level training evidence supports the title. Do not add a date until verified.",
    updatedAt,
  },
  {
    id: "pi-powerbi-training",
    kind: "Certification",
    label: "Introduction to Power BI",
    value: "Introduction to Power BI training",
    safeWording: "Introduction to Power BI.",
    sourceIds: ["source-m01", "source-education-register"],
    evidenceIds: [],
    status: "Approved",
    confidence: "Medium",
    notes: "Treat as completed training, not a professional certification from Microsoft.",
    updatedAt,
  },
  {
    id: "pi-prince2-foundation",
    kind: "Certification",
    label: "PRINCE2 Foundation",
    value: "Completion status unresolved",
    sourceIds: ["source-m10", "source-m11", "source-education-register"],
    evidenceIds: [],
    status: "Conflict",
    confidence: "Low",
    notes: "Do not present as completed until certificate evidence is supplied.",
    updatedAt,
  },
  {
    id: "pi-prince2-practitioner",
    kind: "Certification",
    label: "PRINCE2 Practitioner",
    value: "In progress / pursuing in older evidence",
    sourceIds: ["source-education-register"],
    evidenceIds: [],
    status: "Needs Evidence",
    confidence: "Low",
    notes: "Do not list as completed.",
    updatedAt,
  },
  {
    id: "pi-apm-pmq",
    kind: "Certification",
    label: "APM Project Management Qualification (PMQ)",
    value: "Reading / in progress in older resumes",
    sourceIds: ["source-education-register"],
    evidenceIds: [],
    status: "Needs Evidence",
    confidence: "Low",
    notes: "Not a completed qualification.",
    updatedAt,
  },
];
