import type { CareerOsData } from "./types";

const now = "2026-08-16T10:00:00.000Z";

export function createSeedData(): CareerOsData {
  return {
    profile: {
      name: "Vinnie Jegathees",
      location: "London, UK",
      headline: "Project Delivery | Product & Technology | Innovation",
      summary:
        "Digital marketing and technology management professional and part-time UCL MSc Technology Management candidate, combining multi-market digital acquisition experience with technology evaluation, new product development, analytics, stakeholder management, project delivery, and product and innovation work.",
      employment: [
        {
          id: "emp-nul",
          title: "Performance Marketing Manager",
          company: "Northeastern University London",
          employmentType: "Contract",
          start: "Jun 2025",
          end: "Dec 2025",
          location: "London, UK",
          summary:
            "Managed paid acquisition across PPC, paid social, display and third-party platforms for a multi-market student recruitment portfolio.",
          highlights: [
            "Managed a £140k+ annual digital media budget across PPC, paid social, display and third-party platforms.",
            "Produced RAG-status analysis and multi-market reporting across UK, India and UAE.",
            "Ran agency performance reviews and managed vendor delivery against agreed targets.",
            "Collaborated with website and stakeholder teams on landing-page delivery and A/B testing.",
          ],
          skills: [
            "PPC",
            "Paid social",
            "Programmatic",
            "Budget ownership",
            "RAG reporting",
            "A/B testing",
            "Stakeholder management",
            "GA4",
          ],
        },
        {
          id: "emp-idea",
          title: "Marketing & Operations Executive",
          company: "IDEA StatiCa UK",
          employmentType: "Contract",
          start: "Sep 2023",
          end: "Jun 2024",
          location: "UK",
          summary:
            "Delivered enterprise software-adoption projects with structural-engineering clients alongside analytics and operations work.",
          highlights: [
            "Ran software-adoption projects with structural-engineering clients, covering client engagement, milestones and training.",
            "Built Power BI analytics integrating HubSpot and Salesforce data.",
            "Delivered work in Agile cycles using Asana workflows.",
            "Coordinated cross-functional prospecting with sales, support and marketing.",
          ],
          skills: [
            "Project delivery",
            "Agile",
            "Power BI",
            "HubSpot",
            "Salesforce",
            "Client engagement",
            "Asana",
            "Technology adoption",
          ],
        },
        {
          id: "emp-buchanan",
          title: "Senior Digital Marketing Executive",
          company: "Buchanan Staffing Group",
          employmentType: "Contract",
          start: "Feb 2023",
          end: "May 2023",
          location: "London, UK",
          summary: "CRM migration and marketing funnel work for a recruitment group.",
          highlights: [
            "Supported CRM migration involving Salesforce and Zoho.",
            "Developed marketing funnel and collateral assets.",
            "Coordinated agencies and recruitment managers through delivery.",
          ],
          skills: ["CRM migration", "Salesforce", "Zoho", "Vendor management", "Funnel design"],
        },
        {
          id: "emp-nas",
          title: "Digital Advertising Officer",
          company: "National Autistic Society",
          employmentType: "Unspecified",
          start: "Apr 2022",
          end: "Feb 2023",
          location: "London, UK",
          summary: "Paid search improvement and cross-functional campaign delivery.",
          highlights: [
            "Improved paid search performance across charity campaign portfolios.",
            "Delivered campaigns cross-functionally with fundraising and content teams.",
          ],
          skills: ["Paid search", "Campaign delivery", "Cross-functional working"],
        },
        {
          id: "emp-infinite",
          title: "Senior Digital Marketing Executive",
          company: "Infinite Entertainment UK",
          employmentType: "Unspecified",
          start: "Jun 2016",
          end: "Apr 2022",
          location: "London, UK",
          summary: "Digital and influencer strategy for live entertainment events.",
          highlights: [
            "Led digital and influencer strategy for live events.",
            "Managed delivery workflows in ClickUp across marketing and production teams.",
          ],
          skills: ["Digital strategy", "Influencer marketing", "Event delivery", "ClickUp"],
        },
      ],
      education: [
        {
          id: "edu-ucl",
          qualification: "MSc Technology Management",
          institution: "University College London",
          detail: "Part-time, in progress",
          period: "In progress",
        },
        {
          id: "edu-essex",
          qualification: "BSc Marketing and Management (2:1)",
          institution: "University of Essex",
          detail: "Upper second-class honours",
          period: "Completed",
        },
      ],
      certifications: [
        {
          id: "cert-pfq",
          name: "APM Project Fundamentals Qualification (PFQ)",
          issuer: "Association for Project Management",
          completed: "Completed",
        },
        {
          id: "cert-gpm",
          name: "Google Project Management Professional Certificate",
          issuer: "Google / Coursera",
          completed: "Nov 2024",
        },
        {
          id: "cert-ga",
          name: "Google Analytics 3 & 4",
          issuer: "Google",
          completed: "Completed",
        },
        {
          id: "cert-hotjar",
          name: "Hotjar Levels 1 & 2",
          issuer: "Hotjar",
          completed: "Completed",
        },
        {
          id: "cert-pbi",
          name: "Introduction to Power BI",
          issuer: "Microsoft training",
          completed: "Completed",
        },
      ],
      projects: [
        {
          id: "proj-unidrop",
          name: "UniDrop",
          summary:
            "UCL academic concept for an AI-enabled campus logistics service, covering new product development, MVP definition and user journey mapping.",
          skills: ["New product development", "MVP definition", "User journey mapping"],
        },
        {
          id: "proj-intentionally",
          name: "Intentionally",
          summary:
            "Founder-led mobile-first dating MVP centred on guided Vibe Checks, mutual Continue or Pass and safety; defined the core journey, MVP scope, roadmap and product documentation, and developed a clickable prototype using a Next.js and Supabase project stack.",
          skills: [
            "Product vision",
            "MVP definition",
            "User journey mapping",
            "Product roadmapping",
            "Safety requirements",
            "Prototyping",
          ],
        },
        {
          id: "proj-atlas",
          name: "Atlas",
          summary:
            "Internal founder review and decision-support concept for Intentionally; produced a static prototype, evidence-first product specification and gated prototype-to-production roadmap. It is not a production system.",
          skills: [
            "Product specification",
            "Prototyping",
            "Decision governance",
            "Product roadmapping",
          ],
        },
        {
          id: "proj-bioprinting",
          name: "3D Bioprinting",
          summary:
            "UCL group emerging-technology review of 3D bioprinting using TRL, AD² and S-curve analysis alongside market, risk and roadmapping frameworks.",
          skills: ["Technology evaluation", "TRL", "AD²", "S-curve analysis", "Risk assessment"],
        },
      ],
      skills: [
        "Stakeholder management",
        "Agile delivery",
        "Waterfall delivery",
        "RAG reporting",
        "Vendor management",
        "Agency management",
        "Budget ownership",
        "PPC",
        "Paid social",
        "Programmatic",
        "SEO",
        "A/B testing",
        "New product development",
        "MVP definition",
        "User journey mapping",
        "Technology evaluation",
        "TRL",
        "AD²",
        "S-curve analysis",
        "Product roadmapping",
        "Value proposition development",
        "Risk assessment",
      ],
      tools: [
        "Power BI",
        "Salesforce",
        "HubSpot",
        "GA4",
        "DV360",
        "Google Ads",
        "Meta Ads",
        "Hotjar",
        "Asana",
        "MS Project",
        "ClickUp",
        "Zoho",
      ],
      domains: [
        "Higher education",
        "Engineering software (SaaS)",
        "Recruitment",
        "Charity / non-profit",
        "Live entertainment",
      ],
    },
    profileVersions: [
      {
        id: "pv-1",
        createdAt: now,
        label: "v1 — Seeded baseline",
        note: "Initial career record seeded locally. Approved by Vinnie.",
      },
    ],
    evidence: [
      {
        id: "ev-budget",
        employer: "Northeastern University London",
        category: "Commercial",
        claim:
          "Owned annual digital media budget across PPC, paid social, display and third-party platforms",
        metricValue: "£140k+ annual budget",
        metricBasis: "Supplied master CV and direct user confirmation",
        source: "VINNIE JEGATHEES master CV, confirmed 16 Aug 2026",
        notes: "Verified from the supplied career record and Vinnie's direct confirmation.",
        confidence: "High",
        status: "Verified",
        skills: ["Budget ownership", "PPC", "Paid social", "Programmatic", "Vendor management"],
        updatedAt: now,
      },
      {
        id: "ev-rag",
        employer: "Northeastern University London",
        category: "Delivery",
        claim:
          "Produced RAG-status reporting across UK, India and UAE markets for senior stakeholders",
        metricBasis: "Monthly reporting pack",
        source: "Monthly performance pack",
        confidence: "High",
        status: "Verified",
        skills: ["RAG reporting", "Stakeholder management", "Multi-market reporting"],
        updatedAt: now,
      },
      {
        id: "ev-agency",
        employer: "Northeastern University London",
        category: "Stakeholder Management",
        claim: "Ran agency performance reviews and held vendors to agreed delivery targets",
        source: "Quarterly agency review notes",
        confidence: "High",
        status: "Verified",
        skills: ["Agency management", "Vendor management", "Stakeholder management"],
        updatedAt: now,
      },
      {
        id: "ev-ab",
        employer: "Northeastern University London",
        category: "Analytics",
        claim: "Delivered landing-page and A/B testing work with website and stakeholder teams",
        source: "Test log and website backlog",
        confidence: "Medium",
        status: "Verified",
        skills: ["A/B testing", "GA4", "Conversion optimisation"],
        updatedAt: now,
      },
      {
        id: "ev-cvr",
        employer: "Northeastern University London",
        category: "Performance Marketing",
        claim: "Improved enquiry conversion rate following landing-page testing programme",
        metricValue: "27% increase in conversion rates",
        metricBasis: "Supplied master CV and direct user confirmation",
        source: "VINNIE JEGATHEES master CV, confirmed 16 Aug 2026",
        notes: "Verified from the supplied career record and Vinnie's direct confirmation.",
        confidence: "High",
        status: "Verified",
        skills: ["A/B testing", "GA4", "Conversion optimisation"],
        updatedAt: now,
      },
      {
        id: "ev-adoption",
        employer: "IDEA StatiCa UK",
        category: "Delivery",
        claim:
          "Delivered enterprise software-adoption projects with structural-engineering clients, covering engagement, milestones and training",
        source: "Client project plans and training records",
        confidence: "High",
        status: "Verified",
        skills: ["Project delivery", "Client engagement", "Technology adoption", "Training"],
        updatedAt: now,
      },
      {
        id: "ev-powerbi",
        employer: "IDEA StatiCa UK",
        category: "Analytics",
        claim:
          "Built Power BI reporting integrating HubSpot and Salesforce data for commercial visibility",
        source: "Power BI workspace and data model notes",
        confidence: "High",
        status: "Verified",
        skills: ["Power BI", "HubSpot", "Salesforce", "Data integration"],
        updatedAt: now,
      },
      {
        id: "ev-agile",
        employer: "IDEA StatiCa UK",
        category: "Delivery",
        claim:
          "Ran delivery in Agile cycles using Asana workflows across sales, support and marketing",
        source: "Asana workspace history",
        confidence: "High",
        status: "Verified",
        skills: ["Agile", "Asana", "Cross-functional delivery"],
        updatedAt: now,
      },
      {
        id: "ev-crm",
        employer: "Buchanan Staffing Group",
        category: "Technology",
        claim:
          "Supported CRM migration involving Salesforce and Zoho with agency and manager coordination",
        source: "Migration plan and handover notes",
        confidence: "Medium",
        status: "Verified",
        skills: ["CRM migration", "Salesforce", "Zoho", "Stakeholder management"],
        updatedAt: now,
      },
      {
        id: "ev-nas",
        employer: "National Autistic Society",
        category: "Performance Marketing",
        claim:
          "Rebuilt underperforming paid-search content and keyword strategy with an external agency",
        metricValue: "30% increase in clicks and 60% increase in impressions",
        metricBasis: "Supplied master CV and direct user confirmation",
        source: "VINNIE JEGATHEES master CV, confirmed 16 Aug 2026",
        notes: "Verified from the supplied career record and Vinnie's direct confirmation.",
        confidence: "High",
        status: "Verified",
        skills: ["Paid search", "Campaign delivery"],
        updatedAt: now,
      },
      {
        id: "ev-npd",
        employer: "UCL MSc Technology Management",
        category: "Product & Innovation",
        claim:
          "Defined MVP scope and user journeys for UniDrop, an AI-enabled campus logistics service concept",
        source: "UCL module submission",
        confidence: "High",
        status: "Verified",
        skills: ["New product development", "MVP definition", "User journey mapping"],
        updatedAt: now,
      },
      {
        id: "ev-trl",
        employer: "UCL MSc Technology Management",
        category: "Technology",
        claim:
          "Contributed to a UCL group assessment of 3D bioprinting maturity using TRL, AD² and S-curve analysis, including market, risk and roadmapping work",
        source: "UCL 3D Bioprinting group report, July 2026",
        confidence: "High",
        status: "Verified",
        skills: ["Technology evaluation", "TRL", "AD²", "S-curve analysis", "Risk assessment"],
        updatedAt: now,
      },
      {
        id: "ev-intentionally",
        employer: "Founder project: Intentionally",
        category: "Product & Innovation",
        claim:
          "Founded and led product development for a mobile-first dating MVP; defined the core journey, MVP scope, roadmap, safety requirements and product documentation, and developed a clickable prototype using a Next.js and Supabase project stack",
        source: "Vinnie CV Evidence Audit, 23 Jul 2026 (P03, P05-P10)",
        notes:
          "Pre-commercial founder project. Do not claim a managed team, paying users, commercial performance or production-grade delivery.",
        confidence: "High",
        status: "Verified",
        skills: [
          "Product vision",
          "MVP definition",
          "User journey mapping",
          "Product roadmapping",
          "Safety requirements",
          "Prototyping",
        ],
        updatedAt: now,
      },
      {
        id: "ev-atlas",
        employer: "Internal founder project: Atlas",
        category: "Product & Innovation",
        claim:
          "Defined and prototyped an internal founder review and decision-support concept, producing a static three-flow prototype, evidence-first product specification and gated prototype-to-production roadmap",
        source: "Vinnie CV Evidence Audit, 23 Jul 2026 (P10-P17)",
        notes:
          "Static prototype and planning evidence only. Do not describe Atlas as an operational or commercial platform.",
        confidence: "Medium",
        status: "Verified",
        skills: [
          "Product specification",
          "Prototyping",
          "Decision governance",
          "Product roadmapping",
        ],
        updatedAt: now,
      },
      {
        id: "ev-events",
        employer: "Infinite Entertainment UK",
        category: "Delivery",
        claim: "Led digital and influencer strategy for live events, managing delivery in ClickUp",
        source: "Campaign archive",
        confidence: "Medium",
        status: "Archived",
        skills: ["Digital strategy", "Influencer marketing", "ClickUp"],
        updatedAt: now,
      },
      {
        id: "ev-pmo",
        employer: "General",
        category: "Delivery",
        claim: "Managed a formal PMO governance function",
        source: "None",
        notes: "Excluded — not an accurate description of past responsibilities.",
        confidence: "Low",
        status: "Excluded",
        skills: ["Programme management"],
        updatedAt: now,
      },
    ],
    jobs: [
      {
        id: "job-seed-1",
        company: "Monzo",
        title: "Product Marketing Manager",
        location: "London (Hybrid)",
        url: "https://example.com/monzo/product-marketing-manager",
        sourceType: "paste",
        createdAt: now,
        description:
          "We are looking for a Product Marketing Manager to own go-to-market for new products. You will work with product managers, analysts and agencies to define positioning and value propositions, run A/B testing, manage budget across paid social and PPC, report performance to senior stakeholders, and use GA4 and SQL dashboards to measure impact. Experience with stakeholder management, roadmapping, MVP definition and agile delivery is required. Degree-level education expected.",
      },
    ],
    applications: [
      {
        id: "app-seed-1",
        jobId: "job-seed-1",
        company: "Monzo",
        title: "Product Marketing Manager",
        location: "London (Hybrid)",
        workingArrangement: "Hybrid",
        employmentType: "Permanent",
        priority: "High",
        stage: "Preparing",
        dateAdded: now,
        deadline: "2026-08-24",
        salary: "£60,000 – £70,000",
        source: "Company careers site",
        contact: "Talent team",
        url: "https://example.com/monzo/product-marketing-manager",
        notes:
          "Strong overlap with product marketing and analytics evidence. Needs tailored positioning on B2C fintech.",
        nextAction: "Tailor CV from verified evidence",
        nextActionDue: "2026-08-14",
        history: [{ at: now, entry: "Application created from seeded job scan." }],
      },
    ],
    cvs: [
      {
        id: "cv-seed-1",
        name: "Master CV — General",
        category: "General",
        status: "Approved",
        updatedAt: now,
        versions: [
          {
            id: "cvv-seed-1",
            version: 1,
            createdAt: now,
            note: "Seeded master CV built from verified evidence only.",
            evidenceIds: ["ev-rag", "ev-adoption", "ev-powerbi"],
            body: "",
          },
        ],
      },
    ],
    coverLetters: [],
    scans: [],
    activity: [
      { id: "act-1", at: now, text: "CareerOS seeded with local career record and evidence bank." },
      { id: "act-2", at: now, text: "Application created: Product Marketing Manager at Monzo." },
    ],
    settings: {
      claudeReviewEnabled: false,
      googleDriveFolder: "",
      driveConnected: false,
      dataSource: "Local seeded data",
    },
  };
}
