import type { CareerOsData } from "./types";

const now = "2026-08-10T09:00:00.000Z";

export function createSeedData(): CareerOsData {
  return {
    profile: {
      name: "Vinnie Jegathees",
      location: "London, UK",
      headline: "Project & Technology Delivery | APM PFQ | UCL MSc Technology Management candidate",
      summary:
        "APM PFQ-qualified technology management professional and part-time UCL MSc Technology Management candidate with experience coordinating project delivery, reporting, budgets, stakeholders and technology change across higher education, enterprise software and recruitment. Previously managed a £140k+ digital media portfolio at Northeastern University London and delivered software-adoption, CRM-migration, reporting and workflow-improvement initiatives.",
      employment: [
        {
          id: "emp-nul",
          title: "Performance Marketing Manager",
          company: "Northeastern University London",
          employmentType: "Contract",
          start: "Jun 2025",
          end: "Dec 2025",
          location: "London, UK",
          summary:
            "Managed paid acquisition, reporting, budget allocation and cross-functional delivery across a multi-market student recruitment portfolio.",
          highlights: [
            "Managed an annual digital media budget of £140k+ across PPC, paid social, display and third-party platforms.",
            "Produced RAG-status analysis and multi-market reporting across UK, India and UAE.",
            "Ran agency performance reviews and managed vendor delivery against agreed targets.",
            "Collaborated with website and stakeholder teams on landing-page delivery and A/B testing.",
          ],
          skills: [
            "PPC",
            "Paid social",
            "Programmatic",
            "Budget ownership",
            "RAG reporting",
            "A/B testing",
            "Stakeholder management",
            "GA4",
          ],
        },
        {
          id: "emp-idea",
          title: "Marketing & Operations Executive",
          company: "IDEA StatiCa UK",
          employmentType: "Contract",
          start: "Sep 2023",
          end: "Jun 2024",
          location: "UK",
          summary:
            "Delivered enterprise software-adoption projects with structural-engineering clients alongside analytics and operations work.",
          highlights: [
            "Ran software-adoption projects with structural-engineering clients, covering client engagement, milestones and training.",
            "Built Power BI analytics integrating HubSpot and Salesforce data.",
            "Delivered work in Agile cycles using Asana workflows.",
            "Coordinated cross-functional prospecting with sales, support and marketing.",
          ],
          skills: [
            "Project delivery",
            "Agile",
            "Power BI",
            "HubSpot",
            "Salesforce",
            "Client engagement",
            "Asana",
            "Technology adoption",
          ],
        },
        {
          id: "emp-buchanan",
          title: "Senior Digital Marketing Executive",
          company: "Buchanan Staffing Group",
          employmentType: "Contract",
          start: "Feb 2023",
          end: "May 2023",
          location: "London, UK",
          summary: "CRM migration and marketing funnel work for a recruitment group.",
          highlights: [
            "Supported CRM migration involving Salesforce and Zoho.",
            "Developed marketing funnel and collateral assets.",
            "Coordinated agencies and recruitment managers through delivery.",
          ],
          skills: ["CRM migration", "Salesforce", "Zoho", "Vendor management", "Funnel design"],
        },
        {
          id: "emp-nas",
          title: "Digital Advertising Officer",
          company: "National Autistic Society",
          employmentType: "Permanent",
          start: "Apr 2022",
          end: "Feb 2023",
          location: "London, UK",
          summary: "Paid search improvement and cross-functional campaign delivery.",
          highlights: [
            "Improved paid search performance across charity campaign portfolios.",
            "Delivered campaigns cross-functionally with fundraising and content teams.",
          ],
          skills: ["Paid search", "Campaign delivery", "Cross-functional working"],
        },
        {
          id: "emp-infinite",
          title: "Senior Digital Marketing Executive",
          company: "Infinite Entertainment UK",
          employmentType: "Permanent",
          start: "Jun 2016",
          end: "Apr 2022",
          location: "London, UK",
          summary: "Digital and influencer strategy for live entertainment events.",
          highlights: [
            "Led digital and influencer strategy for live events.",
            "Managed delivery workflows in ClickUp across marketing and production teams.",
          ],
          skills: ["Digital strategy", "Influencer marketing", "Event delivery", "ClickUp"],
        },
      ],
      education: [
        {
          id: "edu-ucl",
          qualification: "MSc Technology Management",
          institution: "University College London",
          detail: "Part-time, in progress",
          period: "In progress",
        },
        {
          id: "edu-essex",
          qualification: "BSc Marketing and Management (2:1)",
          institution: "University of Essex",
          detail: "Upper second-class honours",
          period: "Completed",
        },
      ],
      certifications: [
        {
          id: "cert-pfq",
          name: "APM Project Fundamentals Qualification (PFQ)",
          issuer: "Association for Project Management",
          completed: "Completed",
        },
        {
          id: "cert-gpm",
          name: "Google Project Management Professional Certificate",
          issuer: "Google / Coursera",
          completed: "Nov 2024",
        },
        {
          id: "cert-ga",
          name: "Google Analytics 3 & 4",
          issuer: "Google",
          completed: "Completed",
        },
        {
          id: "cert-hotjar",
          name: "Hotjar Levels 1 & 2",
          issuer: "Hotjar",
          completed: "Completed",
        },
        {
          id: "cert-pbi",
          name: "Introduction to Power BI",
          issuer: "Microsoft training",
          completed: "Completed",
        },
      ],
      projects: [
        {
          id: "proj-unidrop",
          name: "UniDrop",
          summary:
            "AI-enabled campus logistics service concept, covering MVP definition and user journey mapping.",
          skills: ["New product development", "MVP definition", "User journey mapping"],
        },
        {
          id: "proj-intentionally",
          name: "Intentionally",
          summary: "Video-first dating app concept with value proposition development and roadmap.",
          skills: ["Product roadmapping", "Value proposition development"],
        },
        {
          id: "proj-bioprinting",
          name: "3D Bioprinting",
          summary: "Emerging technology maturity assessment using TRL and the Gartner Hype Cycle.",
          skills: ["Technology evaluation", "TRL", "Gartner Hype Cycle", "Risk assessment"],
        },
      ],
      skills: [
        "Stakeholder management",
        "Agile delivery",
        "Waterfall delivery",
        "RAG reporting",
        "Vendor management",
        "Agency management",
        "Budget ownership",
        "PPC",
        "Paid social",
        "Programmatic",
        "SEO",
        "A/B testing",
        "New product development",
        "MVP definition",
        "User journey mapping",
        "Technology evaluation",
        "TRL",
        "Gartner Hype Cycle",
        "Product roadmapping",
        "Value proposition development",
        "Risk assessment",
      ],
      tools: [
        "Power BI",
        "Salesforce",
        "HubSpot",
        "GA4",
        "DV360",
        "Google Ads",
        "Meta Ads",
        "Hotjar",
        "Asana",
        "MS Project",
        "ClickUp",
        "Zoho",
      ],
      domains: [
        "Higher education",
        "Engineering software (SaaS)",
        "Recruitment",
        "Charity / non-profit",
        "Live entertainment",
      ],
    },
    profileVersions: [
      {
        id: "pv-1",
        createdAt: now,
        label: "v1 - Seeded baseline",
        note: "Initial career record seeded locally. Approved by Vinnie.",
      },
      {
        id: "pv-2026-08-12-career-sync",
        createdAt: now,
        label: "v2 - August 2026 career sync",
        note: "Corrected Northeastern end date to Dec 2025 and aligned CareerOS toward project and technology delivery. Approved by Vinnie.",
      },
    ],
    evidence: [
      {
        id: "ev-budget",
        employer: "Northeastern University London",
        category: "Commercial",
        claim:
          "Owned annual digital media budget across PPC, paid social, display and third-party platforms",
        metricValue: "£140k+ annual budget",
        metricBasis: "Media plan and finance tracker",
        source: "Annual media plan, 2025/26",
        confidence: "High",
        status: "Verified",
        skills: ["Budget ownership", "PPC", "Paid social", "Programmatic", "Vendor management"],
        updatedAt: now,
      },
      {
        id: "ev-rag",
        employer: "Northeastern University London",
        category: "Delivery",
        claim:
          "Produced RAG-status reporting across UK, India and UAE markets for senior stakeholders",
        metricBasis: "Monthly reporting pack",
        source: "Monthly performance pack",
        confidence: "High",
        status: "Verified",
        skills: ["RAG reporting", "Stakeholder management", "Multi-market reporting"],
        updatedAt: now,
      },
      {
        id: "ev-agency",
        employer: "Northeastern University London",
        category: "Stakeholder Management",
        claim: "Ran agency performance reviews and held vendors to agreed delivery targets",
        source: "Quarterly agency review notes",
        confidence: "High",
        status: "Verified",
        skills: ["Agency management", "Vendor management", "Stakeholder management"],
        updatedAt: now,
      },
      {
        id: "ev-ab",
        employer: "Northeastern University London",
        category: "Analytics",
        claim: "Delivered landing-page and A/B testing work with website and stakeholder teams",
        source: "Test log and website backlog",
        confidence: "Medium",
        status: "Verified",
        skills: ["A/B testing", "GA4", "Conversion optimisation"],
        updatedAt: now,
      },
      {
        id: "ev-cvr",
        employer: "Northeastern University London",
        category: "Performance Marketing",
        claim: "Improved enquiry conversion rate following landing-page testing programme",
        metricValue: "Percentage uplift not yet confirmed",
        metricBasis: "Requires GA4 export to confirm exact figure",
        source: "Pending - GA4 comparison export",
        notes: "Cannot be used in generated documents until the uplift figure is confirmed.",
        confidence: "Low",
        status: "Needs Evidence",
        skills: ["A/B testing", "GA4", "Conversion optimisation"],
        updatedAt: now,
      },
      {
        id: "ev-adoption",
        employer: "IDEA StatiCa UK",
        category: "Delivery",
        claim:
          "Delivered enterprise software-adoption projects with structural-engineering clients, covering engagement, milestones and training",
        source: "Client project plans and training records",
        confidence: "High",
        status: "Verified",
        skills: ["Project delivery", "Client engagement", "Technology adoption", "Training"],
        updatedAt: now,
      },
      {
        id: "ev-powerbi",
        employer: "IDEA StatiCa UK",
        category: "Analytics",
        claim:
          "Built Power BI reporting integrating HubSpot and Salesforce data for commercial visibility",
        source: "Power BI workspace and data model notes",
        confidence: "High",
        status: "Verified",
        skills: ["Power BI", "HubSpot", "Salesforce", "Data integration"],
        updatedAt: now,
      },
      {
        id: "ev-agile",
        employer: "IDEA StatiCa UK",
        category: "Delivery",
        claim:
          "Ran delivery in Agile cycles using Asana workflows across sales, support and marketing",
        source: "Asana workspace history",
        confidence: "High",
        status: "Verified",
        skills: ["Agile", "Asana", "Cross-functional delivery"],
        updatedAt: now,
      },
      {
        id: "ev-crm",
        employer: "Buchanan Staffing Group",
        category: "Technology",
        claim:
          "Supported CRM migration involving Salesforce and Zoho with agency and manager coordination",
        source: "Migration plan and handover notes",
        confidence: "Medium",
        status: "Verified",
        skills: ["CRM migration", "Salesforce", "Zoho", "Stakeholder management"],
        updatedAt: now,
      },
      {
        id: "ev-nas",
        employer: "National Autistic Society",
        category: "Performance Marketing",
        claim: "Improved paid search performance and delivered campaigns cross-functionally",
        metricValue: "Improvement size not yet confirmed",
        source: "Pending - historic Google Ads export",
        notes: "Directional claim only. Do not quantify in generated documents.",
        confidence: "Low",
        status: "Needs Evidence",
        skills: ["Paid search", "Campaign delivery"],
        updatedAt: now,
      },
      {
        id: "ev-npd",
        employer: "UCL MSc Technology Management",
        category: "Product & Innovation",
        claim:
          "Defined MVP scope and user journeys for UniDrop, an AI-enabled campus logistics service concept",
        source: "UCL module submission",
        confidence: "High",
        status: "Verified",
        skills: ["New product development", "MVP definition", "User journey mapping"],
        updatedAt: now,
      },
      {
        id: "ev-trl",
        employer: "UCL MSc Technology Management",
        category: "Technology",
        claim:
          "Assessed 3D bioprinting maturity using TRL and the Gartner Hype Cycle, including risk assessment",
        source: "UCL technology assessment report",
        confidence: "High",
        status: "Verified",
        skills: ["Technology evaluation", "TRL", "Gartner Hype Cycle", "Risk assessment"],
        updatedAt: now,
      },
      {
        id: "ev-events",
        employer: "Infinite Entertainment UK",
        category: "Delivery",
        claim: "Led digital and influencer strategy for live events, managing delivery in ClickUp",
        source: "Campaign archive",
        confidence: "Medium",
        status: "Archived",
        skills: ["Digital strategy", "Influencer marketing", "ClickUp"],
        updatedAt: now,
      },
      {
        id: "ev-pmo",
        employer: "General",
        category: "Delivery",
        claim: "Managed a formal PMO governance function",
        source: "None",
        notes: "Excluded - not an accurate description of past responsibilities.",
        confidence: "Low",
        status: "Excluded",
        skills: ["Programme management"],
        updatedAt: now,
      },
    ],
    jobs: [
      {
        id: "job-seed-1",
        company: "Monzo",
        title: "Product Marketing Manager",
        location: "London (Hybrid)",
        url: "https://example.com/monzo/product-marketing-manager",
        sourceType: "paste",
        createdAt: now,
        description:
          "We are looking for a Product Marketing Manager to own go-to-market for new products. You will work with product managers, analysts and agencies to define positioning and value propositions, run A/B testing, manage budget across paid social and PPC, report performance to senior stakeholders, and use GA4 and SQL dashboards to measure impact. Experience with stakeholder management, roadmapping, MVP definition and agile delivery is required. Degree-level education expected.",
      },
      {
        id: "job-southeastern-apm-3577",
        company: "Southeastern",
        title: "Assistant Project Manager",
        location: "London Bridge / London & Kent",
        url: "https://jobs.southeasternrailway.co.uk/jobs/job/Assistant-Project-Manager/3577",
        sourceType: "url",
        createdAt: now,
        description:
          "Support delivery across Southeastern's Major Programmes portfolio, including infrastructure, engineering, digital and business transformation projects. Coordinate project activities and workstreams, maintain plans and documentation, monitor budgets, risks, assumptions, issues, dependencies, milestones and change activity, support governance and reporting, build stakeholder and supplier relationships, and help transition project outcomes into business as usual. The role requires experience supporting structured project delivery, project management principles, planning and organisation, accurate reporting and documentation, stakeholder communication, project controls, Microsoft Office 365 and APM PFQ or an equivalent foundation-level project management qualification.",
      },
    ],
    applications: [
      {
        id: "app-seed-1",
        jobId: "job-seed-1",
        company: "Monzo",
        title: "Product Marketing Manager",
        location: "London (Hybrid)",
        workingArrangement: "Hybrid",
        employmentType: "Permanent",
        priority: "High",
        stage: "Preparing",
        dateAdded: now,
        deadline: "2026-08-24",
        salary: "£60,000 - £70,000",
        source: "Company careers site",
        contact: "Talent team",
        url: "https://example.com/monzo/product-marketing-manager",
        notes:
          "Strong overlap with product marketing and analytics evidence. Needs tailored positioning on B2C fintech.",
        nextAction: "Tailor CV from verified evidence",
        nextActionDue: "2026-08-14",
        history: [{ at: now, entry: "Application created from seeded job scan." }],
      },
      {
        id: "app-southeastern-apm-3577",
        jobId: "job-southeastern-apm-3577",
        company: "Southeastern",
        title: "Assistant Project Manager",
        location: "London Bridge / London & Kent",
        workingArrangement: "Unspecified",
        employmentType: "Permanent",
        priority: "High",
        stage: "Preparing",
        dateAdded: now,
        deadline: "2026-08-24",
        salary: "£40,000 - £44,000 per annum DOE",
        source: "Southeastern careers site",
        url: "https://jobs.southeasternrailway.co.uk/jobs/job/Assistant-Project-Manager/3577",
        linkedCvId: "cv-southeastern-apm-3577",
        notes:
          "High-priority project-delivery application. APM PFQ is an explicit requirement. Rail-sector experience is a gap and must not be implied.",
        nextAction: "Review final application and submit before the closing date",
        history: [
          {
            at: now,
            entry:
              "Southeastern Assistant Project Manager application added during the August 2026 CareerOS data sync.",
          },
        ],
      },
    ],
    cvs: [
      {
        id: "cv-seed-1",
        name: "Master CV - General",
        category: "General",
        status: "Approved",
        updatedAt: now,
        versions: [
          {
            id: "cvv-seed-1",
            version: 1,
            createdAt: now,
            note: "Seeded master CV built from verified evidence only.",
            evidenceIds: ["ev-budget", "ev-rag", "ev-adoption", "ev-powerbi"],
            body: "",
          },
        ],
      },
      {
        id: "cv-southeastern-apm-3577",
        name: "Vinnie Jegathees - Assistant Project Manager CV - Southeastern",
        category: "Project Delivery",
        status: "Approved",
        applicationId: "app-southeastern-apm-3577",
        jobId: "job-southeastern-apm-3577",
        updatedAt: now,
        versions: [
          {
            id: "cvv-southeastern-apm-1",
            version: 1,
            createdAt: now,
            note: "Approved two-page STAR-style application CV. External filename: Vinnie_Jegathees_Assistant_Project_Manager_CV_Southeastern.pdf. Metadata record only. Metrics remain reusable only when linked evidence is Verified.",
            body: "",
            evidenceIds: [
              "ev-budget",
              "ev-rag",
              "ev-agency",
              "ev-ab",
              "ev-adoption",
              "ev-powerbi",
              "ev-agile",
              "ev-crm",
              "ev-npd",
              "ev-trl",
            ],
          },
        ],
      },
    ],
    coverLetters: [],
    scans: [],
    activity: [
      { id: "act-1", at: now, text: "CareerOS seeded with local career record and evidence bank." },
      { id: "act-2", at: now, text: "Application created: Product Marketing Manager at Monzo." },
      {
        id: "act-sync-2026-08-12",
        at: now,
        text: "CareerOS profile corrected and synced to the August 2026 approved career record.",
      },
      {
        id: "act-southeastern-app",
        at: now,
        text: "Application added: Assistant Project Manager at Southeastern.",
      },
      {
        id: "act-southeastern-cv",
        at: now,
        text: "Approved Southeastern Assistant Project Manager CV registered in CareerOS.",
      },
    ],
    settings: {
      claudeReviewEnabled: false,
      googleDriveFolder: "",
      driveConnected: false,
      dataSource: "Local seeded data",
      cvRules: {
        language: "British English",
        noEmDashes: true,
        experienceBulletStyle: "Compact STAR/CAR",
        metricUsage: "Roughly half, verified only",
        neverInventMetrics: true,
        allowUnsupportedScope: false,
        allowFormalLineManagementWithoutEvidence: false,
        fontFamily: "Times New Roman",
        fontSizeMinPt: 10,
        fontSizeMaxPt: 12,
        blackTextOnly: true,
        leftAligned: true,
        allowGraphics: false,
        allowTables: false,
        allowIcons: false,
        allowRatingBars: false,
        targetPages: 2,
        preserveBaseCv: true,
      },
    },
  };
}
